### ISSUE TITLE
Зачем бинарей напушила в репу?

### ISSUE THREAD

**Issue by NLipatov** [ElinaBaht/FullstackApp_Backend#1]
У тебя в репозитории бинарные файлы, они изменяются при каждой компиляции проекта. Их нужно включать в **.gitignore**.

Вот эти две папки, о которых я говорю:
![image](https://user-images.githubusercontent.com/80638093/200142125-86178ecc-4f55-4fb7-a16a-5cd363f33c64.png)

Типовое содержимое **.gitignore** для C#-проектов можно взять тут: https://github.com/github/gitignore/blob/main/VisualStudio.gitignore

**Comment by ElinaBaht** [comment]
Спасибо

вс, 6 нояб. 2022 г. в 00:36, Lipatov Nikita ***@***.***>:
